# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(default='', max_length=100)),
                ('page_id', models.BigIntegerField()),
                ('page_name', models.CharField(default='', max_length=100, null=True)),
                ('page_category', models.CharField(default='', max_length=100, null=True)),
                ('page_posts_json', models.TextField(default='', max_length=8000, null=True)),
                ('page_likes', models.IntegerField()),
                ('page_json', models.TextField(default='', max_length=8000)),
            ],
        ),
        migrations.CreateModel(
            name='tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField(unique=True)),
                ('favorited', models.BooleanField()),
                ('favorite_count', models.IntegerField()),
                ('retweeted', models.BooleanField()),
                ('retweet_count', models.IntegerField()),
                ('source', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=100)),
                ('user_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(default='', max_length=100, unique=True)),
                ('twitter_json', models.TextField(default='', max_length=8000)),
            ],
        ),
        migrations.AddField(
            model_name='tweets',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.twitter'),
        ),
        migrations.AlterUniqueTogether(
            name='pages',
            unique_together=set([('institute_name', 'page_id')]),
        ),
    ]
