# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.IntegerField()),
                ('page_name', models.CharField(default='', max_length=100)),
                ('page_category', models.CharField(default='', max_length=100)),
                ('page_posts_json', models.TextField(default='', max_length=2048)),
                ('page_likes', models.IntegerField()),
            ],
        ),
    ]
