# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fullform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_form', models.CharField(default='', max_length=50, unique=True)),
                ('full_form', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
