# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='page_id',
            field=models.BigIntegerField(),
        ),
    ]
