# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_fullform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='tweet_id',
            field=models.BigIntegerField(),
        ),
    ]
