# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_pages_page_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_json', models.TextField(default='', max_length=2000)),
            ],
        ),
    ]
